### ISSUE TITLE
Type does not change from 'info'

### ISSUE THREAD

**Issue by Adhara3** [mouse0270/bootstrap-growl#64]
Hi,
I initialize growl this way, as suggested in the docs:

     $.growl(false, {
        delay: 4000,
	allow_dismiss: false
    });

then, when my own `success(message)` metod is called I do:

    $.growl({
		icon: "fa fa-check-circle-o fa-lg",
		title: " Success! ",
		message: message,
		type: 'success'
	});

But the notification is always of type `info`.

Thanks
Andrea

**Comment by Adhara3** [comment]
I'm a dumb, sorry.

**Comment by mouse0270** [comment]
Not dump it is the most common mistake made... And is mostly my fault for doing things differently than most plugins.

**Comment by ssi-anik** [comment]
@Adhara3 , I'm dumb too. I can't even understand why my notification can't change from danger to any other types

**Comment by ssi-anik** [comment]
Sorry, I'm dumb too. :sob: I typed 'type' twice.
